[workspace]
resolver = "3"
members = ["echo", "grow_only_counter", "maelstrom", "multi_node_broadcast", "multi_node_kafka", "single_node_broadcast", "single_node_kafka", "single_node_tat", "tarut", "uniqueids"]
