[package]
name = "maelstrom"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "1.0.141" }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["full"] }
