[package]
name = "single_node_kafka"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
serde_json = { version = "1.0.141" }
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.9.1"
maelstrom = { path = "../maelstrom" }

